server:
  port: 10000

spring:
  application:
    name: jd-product
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mi_pms?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root

mybatis-plus: #mybatis com.dlq.jdmall.product.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml #不配默认是这个位置
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
