server:
  port: 14000

spring:
  application:
    name: jd-ware
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置
    druid:
      filters: stat
      max-active: 50
      initial-size: 1
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mi_wms?serverTimezone=GMT%2B8&characterEncoding=utf-8
      username: root
      password: root

mybatis-plus: #mybatis com.dlq.jdmall.product.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml #不配默认是这个位置
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
